### PR TITLE
Replace SUSPENDED state for new suspension logic for member

### PR DESCRIPTION
**Pull request by stavamichal**
- when member is VALID + newly suspended = SUSPENDED
     - when member is EXPIRED + newly suspended = SUSPENDED
     - replace where needed
     - remove where not needed any more
    
    DEPLOYMENT:
     - virtual attribute need to be added to every affected service manualy
     for every instance where services exists

### CODE REVIEW

**Comment by stavamichal** [comment]
Need to be merged together with https://github.com/CESNET/perun/pull/2288

**Comment by zlamalp** [comment]
Core implementation was merged as CESNET/perun#2848.

**Review by zlamalp — CHANGES_REQUESTED** [review]
Changes are OK, but there are many other services, which handle members status and we need to update them too or decide, that its not necessary. Also it should be re-based.

**Comment by stavamichal** [comment]
It should be rebased and ready for review and merging.

**Comment by stavamichal** [comment]
ad other services: We don't need to work with services that are using only VALID users. These services would work the same way for all situations except SUSPENDED users (which are now VALID + suspended). We should talk with administrators of these services to get information if they want to skip suspended users no matter the status in the VO.

**Review by zlamalp — APPROVED** [review]

**Pull request merged**
