### PR TITLE
do not create afs volume when empty afs attributes

### PR DESCRIPTION
**Pull request by mvocu**
skip afs volume creation when appropriate AFS_ parameters are empty

### CODE REVIEW

**Comment by stavamichal** [comment]
Please rebase and add missing changelog for this pull request.

Thank you.

**Comment by mvocu** [comment]
Rebased.

Can you clarify the changelog thing?

**Comment by stavamichal** [comment]
@mvocu 
you need to increase a version in slave/process-afs/changelog
only this way we can update this change to the package

**Comment by mvocu** [comment]
Changelog modified.

**Comment by zlamalp** [comment]
@licehammer @mvocu Maybe we could also update gen script, because right now it will print warnings when empty/undef value is printed, as allowed by new design.

**Comment by zlamalp** [comment]
We should consult AFS expert.

**Pull request merged**
